name: build-and-upload

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '21.7.1'

      - name: Confirm CHUB_AUTH_TOKEN is set
        env:
          CHUB_AUTH_TOKEN: ${{ secrets.CHUB_AUTH_TOKEN }}
        run: |
          if [ -z "${{ secrets.CHUB_AUTH_TOKEN }}" ]; then
            echo "Your CHUB_AUTH_TOKEN secret is not set for this repository."
            exit 1
          fi

      - name: Get or Make Stage ID
        if: ${{ !contains(github.repository, 'template') }}
        env:
          CHUB_AUTH_TOKEN: ${{ secrets.CHUB_AUTH_TOKEN }}
          STAGE_ID: ${{ secrets.STAGE_ID }}
        run: |
          mkdir -p public/
          touch public/chub_meta.yaml

          # Check if github_path already exists
          if grep -q "^github_path:" public/chub_meta.yaml; then
            echo "Repo path already in metadata file."
          else
            # Skip saving repo name for template project
            if [ "${{ github.repository }}" == "CharHubAI/stage-template" ]; then
              echo "Not saving repo name for template project"
            else
              echo "Writing github path 'https://github.com/${{ github.repository }}'"
              echo -e "\ngithub_path: 'https://github.com/${{ github.repository }}'" >> public/chub_meta.yaml

              git config --global --add safe.directory "$(pwd)"
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"

              git fetch origin main
              git add public/chub_meta.yaml
              git commit -m "Add github_path to chub_meta.yaml"

              # Sync before pushing
              git pull --rebase origin main || true
              git push origin main
            fi
          fi

      - name: Char UUIDGen
        run: npx @charhub/uuidgen

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
